# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCodeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('barcode', models.CharField(max_length=90, verbose_name='条码')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='条码状态')),
            ],
            options={
                'verbose_name': 'B-产品-条码',
                'verbose_name_plural': 'B-产品-条码',
                'db_table': 'base_goods_barcode',
            },
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('goods_name', models.CharField(max_length=150, verbose_name='物料名称')),
                ('goods_id', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='物料编码')),
                ('size', models.CharField(blank=True, max_length=150, null=True, verbose_name='规格')),
                ('e_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='英文名')),
                ('p_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='产地名')),
                ('price', models.FloatField(verbose_name='含税单价')),
                ('package_unit', models.IntegerField(blank=True, null=True, verbose_name='装箱规格')),
                ('shelf_life', models.IntegerField(blank=True, null=True, verbose_name='保质期')),
                ('logistics_time', models.IntegerField(blank=True, null=True, verbose_name='物流周期')),
                ('order_time', models.IntegerField(blank=True, null=True, verbose_name='订货周期')),
                ('moq', models.IntegerField(blank=True, null=True, verbose_name='起订量')),
                ('memorandum', models.CharField(blank=True, max_length=360, null=True, verbose_name='备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='货品状态')),
                ('manufactory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.ManuInfo', verbose_name='供应商')),
            ],
            options={
                'verbose_name': 'B-产品-货品',
                'verbose_name_plural': 'B-产品-货品',
                'db_table': 'base_goods_goods',
            },
        ),
        migrations.CreateModel(
            name='SeriesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('s_name', models.CharField(max_length=100, unique=True, verbose_name='系列名称')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='系列类型')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='系列状态')),
            ],
            options={
                'verbose_name': 'B-产品-系列',
                'verbose_name_plural': 'B-产品-系列',
                'db_table': 'base_goods_series',
            },
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.SeriesInfo', verbose_name='系列'),
        ),
    ]
