# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-22 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191229_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='e_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='logistics_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='物流周期（天）'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='order_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='订货周期（天）'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='p_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='产地名'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.SizeInfo', verbose_name='规格'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsinfo',
            unique_together=set([]),
        ),
    ]
