# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200222_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_id',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='物料编码'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='goods_name',
            field=models.CharField(max_length=150, verbose_name='物料名称'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='manufactory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ManuInfo', verbose_name='供应商'),
        ),
        migrations.AlterField(
            model_name='goodsinfo',
            name='price',
            field=models.IntegerField(verbose_name='含税单价'),
        ),
    ]
