# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-01-28 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseinfo',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '普通仓库'), (1, '工厂仓库'), (2, '虚拟仓库'), (3, '残品仓库'), (4, '退货仓库')], default=0, verbose_name='仓库类型'),
        ),
    ]
