# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20191124_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseGeneral',
            fields=[
            ],
            options={
                'verbose_name': 'BASE-仓库-普通仓库',
                'verbose_name_plural': 'BASE-仓库-普通仓库',
                'proxy': True,
                'indexes': [],
            },
            bases=('warehouse.warehouseinfo',),
        ),
        migrations.CreateModel(
            name='WarehouseManu',
            fields=[
            ],
            options={
                'verbose_name': 'BASE-仓库-工厂仓库',
                'verbose_name_plural': 'BASE-仓库-工厂仓库',
                'proxy': True,
                'indexes': [],
            },
            bases=('warehouse.warehouseinfo',),
        ),
        migrations.CreateModel(
            name='WarehouseVirtual',
            fields=[
            ],
            options={
                'verbose_name': 'BASE-仓库-虚拟仓库',
                'verbose_name_plural': 'BASE-仓库-虚拟仓库',
                'proxy': True,
                'indexes': [],
            },
            bases=('warehouse.warehouseinfo',),
        ),
        migrations.AlterField(
            model_name='warehouseinfo',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '普通仓库'), (1, '工厂仓库'), (2, '虚拟仓库')], default=0, verbose_name='仓库类型'),
        ),
        migrations.AlterField(
            model_name='warehouseinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '停用'), (1, '正常')], default=1, verbose_name='仓库状态'),
        ),
        migrations.DeleteModel(
            name='WarehouseTypeInfo',
        ),
    ]
