# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-12 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oristockininfo',
            options={'verbose_name': 'wms-原始采购入库单', 'verbose_name_plural': 'wms-原始采购入库单'},
        ),
        migrations.AlterModelOptions(
            name='oristockinunhandle',
            options={'verbose_name': 'wms-原始采购入库单未递交', 'verbose_name_plural': 'wms-原始采购入库单未递交'},
        ),
    ]
