# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-12 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0002_auto_20200212_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oristockininfo',
            name='batch_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='批号'),
        ),
        migrations.AlterField(
            model_name='oristockininfo',
            name='expiry_date',
            field=models.DateTimeField(blank=True, max_length=60, null=True, verbose_name='有效期至'),
        ),
        migrations.AlterField(
            model_name='oristockininfo',
            name='multiple',
            field=models.IntegerField(blank=True, null=True, verbose_name='主/辅换算率'),
        ),
        migrations.AlterField(
            model_name='oristockininfo',
            name='produce_time',
            field=models.DateTimeField(blank=True, max_length=60, null=True, verbose_name='生产日期'),
        ),
        migrations.AlterField(
            model_name='oristockininfo',
            name='purchase_order_id',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='订单单号'),
        ),
    ]
