# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-01 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0002_auto_20200301_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='oriallocation',
            name='si_tag',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='入库创建'),
        ),
        migrations.AddField(
            model_name='oriallocation',
            name='so_tag',
            field=models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='出库创建'),
        ),
        migrations.AlterField(
            model_name='oriallocation',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '供货商非法'), (3, '部门非法'), (4, '货品非法'), (5, '仓库非法'), (6, '实例保存错误'), (7, '入库保存错误'), (8, '出库保存错误')], default=0, verbose_name='问题原因'),
        ),
    ]
