# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-07 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0003_auto_20200301_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oristockininfo',
            name='goods_unit',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='库存单位'),
        ),
    ]
