# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-12 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0003_auto_20200212_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oristockininfo',
            old_name='produce_time',
            new_name='produce_date',
        ),
        migrations.RenameField(
            model_name='oristockininfo',
            old_name='stockin_time',
            new_name='stockin_date',
        ),
    ]
