# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0004_auto_20200307_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oriallocation',
            name='customer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='客户'),
        ),
    ]
