# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-12 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0004_auto_20200212_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oristockininfo',
            name='payable_quantity',
        ),
        migrations.AddField(
            model_name='oristockininfo',
            name='related_quantity',
            field=models.IntegerField(default=0, verbose_name='关联数量'),
        ),
    ]
