# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-12 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0005_auto_20200212_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oristockininfo',
            name='assist_quantity',
        ),
    ]
