# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-12 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0006_remove_oristockininfo_assist_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oristockininfo',
            old_name='order_creator',
            new_name='ori_creator',
        ),
    ]
