# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0008_auto_20200212_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='oristockout',
            name='address',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='收货方地址'),
        ),
        migrations.AddField(
            model_name='oristockout',
            name='buyer',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='收货方'),
        ),
    ]
