# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-12 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0009_auto_20200212_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oristockout',
            name='amount',
            field=models.FloatField(verbose_name='价税合计'),
        ),
        migrations.AlterField(
            model_name='oristockout',
            name='price',
            field=models.FloatField(verbose_name='含税单价'),
        ),
    ]
