# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-18 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0010_auto_20200212_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oristockout',
            options={'verbose_name': 'wms-原始销售出库单查询', 'verbose_name_plural': 'wms-原始销售出库单查询'},
        ),
        migrations.AlterModelOptions(
            name='oristockoutunhandle',
            options={'verbose_name': 'wms-原始销售出库单未递交', 'verbose_name_plural': 'wms-原始销售出库单未递交'},
        ),
        migrations.AlterField(
            model_name='orinsstockout',
            name='goods_size',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='规格型号'),
        ),
    ]
