# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-18 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0013_auto_20200218_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orirefund',
            old_name='produce_time',
            new_name='produce_date',
        ),
    ]
