# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-19 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0014_auto_20200218_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oirloss',
            old_name='expiry_time',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='oirloss',
            old_name='produce_time',
            new_name='produce_date',
        ),
    ]
