# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-19 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0015_auto_20200219_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oristockout',
            name='package_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='主辅换算率'),
        ),
    ]
