# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0016_auto_20200219_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oristockininfo',
            old_name='demander',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='oripurchaseinfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '工厂非法'), (3, '货品非法'), (4, '递交失败'), (5, '其他错误')], default=0, verbose_name='问题原因'),
        ),
    ]
