# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0017_auto_20200223_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oristockininfo',
            name='department',
            field=models.CharField(max_length=60, verbose_name='收料部门'),
        ),
    ]
