# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0018_auto_20200223_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oristockininfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '供货商非法'), (3, '部门非法'), (4, '货品非法'), (5, '仓库非法'), (6, '采购单错误')], default=0, verbose_name='错误标识'),
        ),
    ]
