# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0020_auto_20200223_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oristockout',
            old_name='ori_order_category',
            new_name='order_category',
        ),
        migrations.AlterField(
            model_name='oristockout',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '部门非法'), (3, '货品非法'), (4, '仓库非法'), (5, '实例存储失败')], default=0, verbose_name='错误原因'),
        ),
    ]
