# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-24 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0021_auto_20200223_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orinsstockout',
            old_name='category',
            new_name='order_category',
        ),
    ]
