# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-24 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0023_auto_20200224_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orinsstockout',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '导入重复'), (2, '部门非法'), (3, '货品非法'), (4, '仓库非法'), (5, '实例保存错误')], default=0, verbose_name='问题原因'),
        ),
    ]
