# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-24 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0024_auto_20200224_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orinpstockin',
            name='category',
        ),
        migrations.AddField(
            model_name='orinpstockin',
            name='order_category',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='单据类型'),
        ),
        migrations.AlterField(
            model_name='orinpstockin',
            name='ori_creator',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='创建人'),
        ),
    ]
