# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-25 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0026_auto_20200224_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orinpstockin',
            old_name='produce_time',
            new_name='produce_date',
        ),
    ]
