# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-25 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0027_auto_20200225_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oirloss',
            old_name='category',
            new_name='order_category',
        ),
        migrations.RenameField(
            model_name='oriallocation',
            old_name='category',
            new_name='order_category',
        ),
        migrations.RenameField(
            model_name='oripurrefund',
            old_name='category',
            new_name='order_category',
        ),
        migrations.RenameField(
            model_name='orirefund',
            old_name='category',
            new_name='order_category',
        ),
        migrations.RenameField(
            model_name='orisurplus',
            old_name='category',
            new_name='order_category',
        ),
    ]
