# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0028_auto_20200225_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orirefund',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '供货商非法'), (3, '部门非法'), (4, '货品非法'), (5, '仓库非法'), (6, '实例保存错误')], default=0, verbose_name='问题原因'),
        ),
    ]
