# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-25 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_console', '0031_auto_20200225_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oirloss',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '部门非法'), (3, '货品非法'), (4, '仓库非法'), (5, '实例存储失败')], default=0, verbose_name='问题原因'),
        ),
        migrations.AlterField(
            model_name='oristockout',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '导入重复'), (2, '部门非法'), (3, '货品非法'), (4, '仓库非法'), (5, '实例保存错误')], default=0, verbose_name='错误原因'),
        ),
        migrations.AlterField(
            model_name='orisurplus',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '供货商非法'), (3, '部门非法'), (4, '货品非法'), (5, '仓库非法'), (6, '实例保存错误')], default=0, verbose_name='问题原因'),
        ),
    ]
