# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentreInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='中心名称')),
                ('category', models.SmallIntegerField(choices=[(0, '非销售'), (1, '销售')], default=1, verbose_name='类型')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '正常')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'B-部门-中心列表',
                'verbose_name_plural': 'B-部门-中心列表',
                'db_table': 'base_centre',
            },
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='部门名称')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '正常')], default=1, verbose_name='状态')),
                ('category', models.IntegerField(choices=[(0, '独立'), (1, '全局')], default=0, verbose_name='部门类型')),
                ('department_id', models.CharField(blank=True, max_length=60, null=True, verbose_name='部门ID')),
                ('centre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.CentreInfo', verbose_name='所属中心')),
            ],
            options={
                'verbose_name': 'B-部门-部门列表',
                'verbose_name_plural': 'B-部门-部门列表',
                'db_table': 'base_department',
            },
        ),
    ]
