# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-19 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='部门名称')),
                ('order_status', models.IntegerField(choices=[(0, '已取消'), (1, '正常')], default=1, verbose_name='状态')),
                ('category', models.IntegerField(choices=[(0, '国内'), (1, '国际')], default=1, verbose_name='部门类型')),
            ],
            options={
                'verbose_name': 'BASE-部门',
                'verbose_name_plural': 'BASE-部门',
                'db_table': 'base_department',
            },
        ),
    ]
