# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-17 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centreinfo',
            name='category',
            field=models.SmallIntegerField(choices=[(0, '独立'), (1, '全局')], default=0, verbose_name='类型'),
        ),
    ]
