# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-22 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentList',
        ),
        migrations.CreateModel(
            name='MyDepartment',
            fields=[
            ],
            options={
                'verbose_name': 'B-部门-本部门',
                'verbose_name_plural': 'B-部门-本部门',
                'proxy': True,
                'indexes': [],
            },
            bases=('department.departmentinfo',),
        ),
        migrations.AlterModelOptions(
            name='departmentinfo',
            options={'verbose_name': 'B-部门-部门列表', 'verbose_name_plural': 'B-部门-部门列表'},
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='category',
            field=models.IntegerField(choices=[(0, '国内'), (1, '国际')], default=0, verbose_name='部门类型'),
        ),
        migrations.AlterField(
            model_name='departmentinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=150, unique=True, verbose_name='部门名称'),
        ),
    ]
