# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-21 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCreateInfo',
            fields=[
            ],
            options={
                'verbose_name': 'B-部门',
                'verbose_name_plural': 'B-部门',
                'proxy': True,
                'indexes': [],
            },
            bases=('department.departmentinfo',),
        ),
        migrations.AlterModelOptions(
            name='departmentinfo',
            options={'verbose_name': 'B-部门查询', 'verbose_name_plural': 'B-部门查询'},
        ),
    ]
