# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-23 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20191121_2139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentCreateInfo',
        ),
        migrations.CreateModel(
            name='DepartmentOperationInfo',
            fields=[
            ],
            options={
                'verbose_name': 'B-部门',
                'verbose_name_plural': 'B-部门',
                'proxy': True,
                'indexes': [],
            },
            bases=('department.departmentinfo',),
        ),
    ]
