# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20200222_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentinfo',
            name='category',
            field=models.IntegerField(choices=[(0, '独立'), (1, '全局')], default=0, verbose_name='部门类型'),
        ),
    ]
