# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20191123_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentinfo',
            options={'verbose_name': 'B-本部门', 'verbose_name_plural': 'B-本部门'},
        ),
        migrations.AlterModelOptions(
            name='departmentoperationinfo',
            options={'verbose_name': 'B-部门查询', 'verbose_name_plural': 'B-部门查询'},
        ),
    ]
