# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-03 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_auto_20191125_0104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepartmentOperationInfo',
        ),
        migrations.CreateModel(
            name='DepartmentList',
            fields=[
            ],
            options={
                'verbose_name': 'B-部门查询',
                'verbose_name_plural': 'B-部门查询',
                'proxy': True,
                'indexes': [],
            },
            bases=('department.departmentinfo',),
        ),
    ]
