# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-29 19:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('stock', '0004_auto_20191229_1658'),
        ('goods', '0002_auto_20191229_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAllot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('allot_order_id', models.CharField(max_length=30, verbose_name='虚拟调拨单号')),
                ('category', models.SmallIntegerField(choices=[(0, '有借无还'), (1, '有借有还'), (2, '还债')], default=0, verbose_name='类型')),
                ('goods_id', models.CharField(db_index=True, max_length=60, verbose_name='物料编码')),
                ('quantity', models.IntegerField(verbose_name='调拨数量')),
                ('memorandum', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '未递交'), (2, '待同意'), (3, '待执行'), (4, '已完成')], default=1, verbose_name='单据状态')),
                ('error_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '可借存货不足'), (2, '可还存货不足')], default=0, verbose_name='错误原因')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='源部门')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='货品名称')),
                ('vwarehouse_des', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vwaredes', to='warehouse.WarehouseVirtual', verbose_name='目的虚拟仓')),
                ('vwarehouse_ori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vwareori', to='stock.DeptStockInfo', verbose_name='源虚拟仓')),
            ],
            options={
                'verbose_name': 'oms-a-调拨查询',
                'verbose_name_plural': 'oms-a-调拨查询',
                'db_table': 'oms_vwm_allot',
            },
        ),
        migrations.CreateModel(
            name='VACheck',
            fields=[
            ],
            options={
                'verbose_name': 'oms-a-未同意调拨',
                'verbose_name_plural': 'oms-a-未同意调拨',
                'proxy': True,
                'indexes': [],
            },
            bases=('allot.virtualallot',),
        ),
        migrations.CreateModel(
            name='VAPending',
            fields=[
            ],
            options={
                'verbose_name': 'oms-a-未递交调拨',
                'verbose_name_plural': 'oms-a-未递交调拨',
                'proxy': True,
                'indexes': [],
            },
            bases=('allot.virtualallot',),
        ),
        migrations.CreateModel(
            name='VAProcess',
            fields=[
            ],
            options={
                'verbose_name': 'oms-a-未执行调拨',
                'verbose_name_plural': 'oms-a-未执行调拨',
                'proxy': True,
                'indexes': [],
            },
            bases=('allot.virtualallot',),
        ),
    ]
