# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-10 10:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vallotsiinfo',
            old_name='va_stockin',
            new_name='va_stockout',
        ),
    ]
