# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-29 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualallot',
            name='checker',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='审核人'),
        ),
    ]
