# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-01 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allot', '0002_auto_20200229_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='VASIMine',
            fields=[
            ],
            options={
                'verbose_name': 'oms-a-未处理部门入库单',
                'verbose_name_plural': 'oms-a-未处理部门入库单',
                'proxy': True,
                'indexes': [],
            },
            bases=('allot.vallotsiinfo',),
        ),
        migrations.AlterField(
            model_name='vallotsiinfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '虚拟入库超出了出库数'), (2, '对应虚拟入库出错'), (3, '虚拟仓库存增加出错，需要联系管理员处理'), (4, '部门仓实例保存错误')], default=0, verbose_name='错误标识'),
        ),
        migrations.AlterField(
            model_name='vallotsiinfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已取消'), (1, '未审核'), (2, '未处理'), (3, '已完成')], db_index=True, default=1, verbose_name='订单状态'),
        ),
    ]
