# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-10 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allot', '0002_auto_20200510_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vallotsiinfo',
            name='va_stockout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allot.VAllotSOInfo', verbose_name='关联出库单'),
        ),
    ]
