# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-01 08:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allot', '0003_auto_20200301_0732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vallotsiinfo',
            options={'verbose_name': 'oms-a-部门入库单查询', 'verbose_name_plural': 'oms-a-部门入库单查询'},
        ),
        migrations.AlterModelOptions(
            name='vallotsoinfo',
            options={'verbose_name': 'oms-a-部门出库单查询', 'verbose_name_plural': 'oms-a-部门出库单查询'},
        ),
    ]
