# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allot', '0004_auto_20200301_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vallotsoinfo',
            name='dept_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.DeptStockInfo', verbose_name='源部门仓'),
        ),
    ]
