# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allot', '0005_auto_20200307_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vallotsiinfo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='目的部门'),
        ),
    ]
