# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0004_auto_20200222_0843'),
        ('purchase', '0001_initial'),
        ('warehouse', '0006_auto_20200223_1054'),
        ('company', '0002_auto_20200222_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('order_category', models.CharField(max_length=60, verbose_name='单据类型')),
                ('order_creator', models.CharField(max_length=60, verbose_name='创建人')),
                ('create_date', models.DateTimeField(max_length=60, verbose_name='创建日期')),
                ('seller', models.CharField(max_length=60, verbose_name='结算方')),
                ('bs_category', models.CharField(max_length=60, verbose_name='业务类型')),
                ('stockin_order_id', models.CharField(max_length=60, unique=True, verbose_name='单据编号')),
                ('last_modifier', models.CharField(max_length=60, verbose_name='最后修改人')),
                ('payee', models.CharField(max_length=60, verbose_name='收款方')),
                ('stockin_time', models.DateTimeField(max_length=60, verbose_name='入库日期')),
                ('last_modify_time', models.DateTimeField(max_length=60, verbose_name='最后修改日期')),
                ('purchaser', models.CharField(max_length=60, verbose_name='采购组织')),
                ('demander', models.CharField(max_length=60, verbose_name='需求组织')),
                ('goods_id', models.CharField(db_index=True, max_length=60, verbose_name='物料编码')),
                ('goods_size', models.CharField(max_length=60, verbose_name='规格型号')),
                ('goods_unit', models.CharField(max_length=60, verbose_name='库存单位')),
                ('quantity_receivable', models.IntegerField(blank=True, null=True, verbose_name='应收数量')),
                ('quantity_received', models.IntegerField(verbose_name='实收数量')),
                ('batch_number', models.CharField(max_length=60, verbose_name='批号')),
                ('expiry_date', models.DateTimeField(max_length=60, verbose_name='有效期至')),
                ('produce_time', models.DateTimeField(max_length=60, verbose_name='生产日期')),
                ('memorandum', models.CharField(blank=True, max_length=60, null=True, verbose_name='备注')),
                ('origin_order_category', models.CharField(max_length=60, verbose_name='源单类型')),
                ('origin_order_id', models.CharField(max_length=60, verbose_name='源单编号')),
                ('payable_quantity', models.IntegerField(verbose_name='关联应付数量（计价基本）')),
                ('assist_quantity', models.IntegerField(verbose_name='实收数量(辅单位)')),
                ('multiple', models.IntegerField(verbose_name='主/辅换算率')),
                ('price', models.IntegerField(verbose_name='成本价')),
                ('quantity_linking', models.IntegerField(default=0, verbose_name='关联存货数量')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '未审核'), (2, '待核销'), (3, '已完成')], db_index=True, default=1, verbose_name='订单状态')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '原始单缺漏'), (2, '入库数量大于采购数量'), (3, '保存库存错误'), (4, '货品错误'), (5, '采购单错误'), (5, '采购单数量错误')], default=0, verbose_name='错误标识')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='物料名称')),
                ('purchase_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.PurchaseInfo', verbose_name='订单单号')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyInfo', verbose_name='供货方')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'wms-入库单查询',
                'verbose_name_plural': 'wms-入库单查询',
                'db_table': 'wms_s_stockin',
            },
        ),
        migrations.CreateModel(
            name='StockInPending',
            fields=[
            ],
            options={
                'verbose_name': 'wms-入库单未审核',
                'verbose_name_plural': 'wms-入库单未审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('stockin.stockininfo',),
        ),
    ]
