# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-03 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oristockininfo',
            name='ownership',
        ),
        migrations.RemoveField(
            model_name='stockininfo',
            name='ownership',
        ),
    ]
