# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-05 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0002_auto_20191203_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oristockininfo',
            old_name='available_status',
            new_name='produce_time',
        ),
        migrations.RenameField(
            model_name='stockininfo',
            old_name='available_status',
            new_name='produce_time',
        ),
    ]
