# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0002_auto_20191228_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oristockininfo',
            name='goods_id',
            field=models.CharField(db_index=True, max_length=60, verbose_name='物料编码'),
        ),
        migrations.AlterField(
            model_name='stockininfo',
            name='goods_id',
            field=models.CharField(db_index=True, max_length=60, verbose_name='物料编码'),
        ),
        migrations.AlterField(
            model_name='stockininfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '原始单缺漏'), (2, '入库数量大于采购数量'), (3, '保存库存错误'), (4, '货品错误'), (5, '采购单错误'), (5, '采购单数量错误')], default=0, verbose_name='错误标识'),
        ),
    ]
