# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-08 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0003_auto_20191229_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oristockininfo',
            name='batch_number',
            field=models.CharField(db_index=True, max_length=60, verbose_name='批号'),
        ),
        migrations.AlterField(
            model_name='oristockininfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已取消'), (1, '未递交'), (2, '已递交')], db_index=True, default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='oristockininfo',
            name='stockin_order_id',
            field=models.CharField(db_index=True, max_length=60, verbose_name='单据编号'),
        ),
        migrations.AlterField(
            model_name='oristockininfo',
            name='to_organization',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='货主'),
        ),
        migrations.AlterField(
            model_name='oristockininfo',
            name='warehouse',
            field=models.CharField(db_index=True, max_length=60, verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='stockininfo',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '已取消'), (1, '未审核'), (2, '待核销'), (3, '已完成')], db_index=True, default=1, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='stockininfo',
            name='to_organization',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='货主'),
        ),
    ]
