# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-05 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0003_auto_20191205_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oristockininfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '工厂错误'), (2, '货主错误'), (3, '仓库错误'), (4, '货品错误'), (5, '采购单错误'), (6, '入库单数量超出采购单数量')], default=0, verbose_name='错误标识'),
        ),
        migrations.AlterField(
            model_name='stockininfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '工厂错误'), (2, '货主错误'), (3, '仓库错误'), (4, '货品错误'), (5, '采购单错误'), (5, '采购单数量错误')], default=0, verbose_name='错误标识'),
        ),
    ]
