# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-08 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0004_auto_20200108_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oristockininfo',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='oristockininfo',
            name='is_cancel',
        ),
        migrations.RemoveField(
            model_name='oristockininfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='oristockininfo',
            name='supplier_address',
        ),
        migrations.RemoveField(
            model_name='oristockininfo',
            name='to_organization',
        ),
        migrations.RemoveField(
            model_name='stockininfo',
            name='consignee',
        ),
        migrations.RemoveField(
            model_name='stockininfo',
            name='is_cancel',
        ),
        migrations.RemoveField(
            model_name='stockininfo',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stockininfo',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='stockininfo',
            name='supplier_address',
        ),
        migrations.RemoveField(
            model_name='stockininfo',
            name='to_organization',
        ),
    ]
