# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-08 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0005_auto_20200108_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockininfo',
            name='stockin_order_id',
            field=models.CharField(max_length=60, unique=True, verbose_name='单据编号'),
        ),
        migrations.AlterUniqueTogether(
            name='stockininfo',
            unique_together=set([]),
        ),
    ]
