# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-01-08 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockin', '0006_auto_20200108_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oristockinpending',
            options={'verbose_name': 'wms-原始入库单未递交', 'verbose_name_plural': 'wms-原始入库单未递交'},
        ),
        migrations.AlterModelOptions(
            name='stockinpending',
            options={'verbose_name': 'wms-入库单未审核', 'verbose_name_plural': 'wms-入库单未审核'},
        ),
    ]
