# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-19 21:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MineInfo',
            fields=[
            ],
            options={
                'verbose_name': 'BASE-公司-本埠主体',
                'verbose_name_plural': 'BASE-公司-本埠主体',
                'proxy': True,
                'indexes': [],
            },
            bases=('company.companyinfo',),
        ),
    ]
