# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('p_name', models.CharField(max_length=60, unique=True, verbose_name='平台名称')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='单据状态')),
            ],
            options={
                'verbose_name': 'B-店铺-平台',
                'verbose_name_plural': 'B-店铺-平台',
                'db_table': 'base_shop_platform',
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='店铺名称')),
                ('shop_id', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='店铺ID')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='单据状态')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.CentreInfo', verbose_name='部门')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.MineInfo', verbose_name='公司')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.PlatformInfo', verbose_name='平台')),
            ],
            options={
                'verbose_name': 'B-店铺-店铺',
                'verbose_name_plural': 'B-店铺-店铺',
                'db_table': 'base_shop_shop',
            },
        ),
    ]
