# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-21 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='shop_name',
            field=models.CharField(max_length=60, unique=True, verbose_name='店铺名称'),
        ),
    ]
