# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-27 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covertsi',
            name='seller',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='结算方'),
        ),
    ]
