# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_console', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covertsi',
            name='order_category',
            field=models.SmallIntegerField(choices=[(0, '独立入库'), (1, '全局入库')], default=0, verbose_name='单据类型'),
        ),
        migrations.AlterField(
            model_name='covertsi',
            name='order_creator',
            field=models.CharField(max_length=60, verbose_name='创建人'),
        ),
    ]
