# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_console', '0002_auto_20200223_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covertsi',
            name='batch_number',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='批号'),
        ),
    ]
