# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-01 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('goods', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('convert_console', '0002_auto_20200227_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovertLoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('order_id', models.CharField(max_length=30, unique=True, verbose_name='单据编号')),
                ('customer', models.CharField(max_length=60, verbose_name='客户')),
                ('origin_order_category', models.CharField(max_length=20, verbose_name='源单类型')),
                ('origin_order_id', models.CharField(max_length=60, verbose_name='源单编号')),
                ('sale_organization', models.CharField(max_length=30, verbose_name='销售组织')),
                ('department', models.CharField(max_length=60, verbose_name='执行部门')),
                ('ori_creator', models.CharField(max_length=30, verbose_name='创建人')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('goods_id', models.CharField(max_length=50, verbose_name='物料编码')),
                ('quantity', models.IntegerField(verbose_name='盘亏数量')),
                ('memorandum', models.CharField(blank=True, max_length=300, null=True, verbose_name='备注')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '多线程重复操作'), (2, '部门存货不足'), (3, '保存历史记录失败'), (4, '保存部门仓失败'), (5, '保存实仓失败'), (6, '保存部门仓失败'), (7, '部门没有此货品')], default=0, verbose_name='错误原因')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '待递交'), (2, '已完成')], default=1, verbose_name='状态')),
                ('des_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='目标部门')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='物料名称')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'oms-盘亏调整单查询',
                'verbose_name_plural': 'oms-盘亏调整单查询',
                'db_table': 'oms_convert_loss',
            },
        ),
        migrations.CreateModel(
            name='CovertLOUnhandle',
            fields=[
            ],
            options={
                'verbose_name': 'oms-未审核盘亏调整单',
                'verbose_name_plural': 'oms-未审核盘亏调整单',
                'proxy': True,
                'indexes': [],
            },
            bases=('convert_console.covertloss',),
        ),
    ]
