# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-05-31 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_console', '0002_auto_20200517_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covertso',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '多线程重复操作'), (2, '部门存货不足'), (3, '保存历史记录失败'), (4, '保存部门仓失败'), (5, '保存实仓失败'), (6, '保存部门仓失败'), (7, '部门没有此货品'), (8, '货品无足够可分配库存'), (9, '生成虚拟调拨出库出错'), (10, '已生成虚拟调拨出库'), (11, '出库数量超出了可调拨数量')], default=0, verbose_name='错误原因'),
        ),
    ]
