# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert_console', '0003_auto_20200223_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covertsi',
            name='order_creator',
        ),
    ]
