# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-05 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_console', '0003_covertloss_covertlounhandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='covertloss',
            name='order_category',
            field=models.SmallIntegerField(choices=[(0, '独立出库'), (1, '全局出库')], default=0, verbose_name='单据类型'),
        ),
    ]
