# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20200223_0904'),
        ('warehouse', '0006_auto_20200223_1054'),
        ('goods', '0004_auto_20200222_0843'),
        ('convert_console', '0004_remove_covertsi_order_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovertSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('order_id', models.CharField(max_length=30, verbose_name='单据编号')),
                ('customer', models.CharField(max_length=60, verbose_name='客户')),
                ('order_category', models.SmallIntegerField(choices=[(0, '独立入库'), (1, '全局入库')], default=0, verbose_name='单据类型')),
                ('ori_order_category', models.CharField(max_length=20, verbose_name='源单类型')),
                ('origin_order_id', models.CharField(max_length=60, verbose_name='源单编号')),
                ('sale_organization', models.CharField(max_length=30, verbose_name='销售组织')),
                ('memorandum', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('ori_creator', models.CharField(max_length=30, verbose_name='创建人')),
                ('date', models.DateTimeField(verbose_name='日期')),
                ('goods_id', models.CharField(max_length=50, verbose_name='物料编码')),
                ('quantity', models.IntegerField(verbose_name='实发数量')),
                ('price', models.FloatField(verbose_name='含税单价')),
                ('amount', models.FloatField(verbose_name='价税合计')),
                ('package_size', models.IntegerField(blank=True, null=True, verbose_name='主辅换算率')),
                ('buyer', models.CharField(blank=True, max_length=60, null=True, verbose_name='收货方')),
                ('address', models.CharField(blank=True, max_length=240, null=True, verbose_name='收货方地址')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '重复递交'), (2, '仓库非法'), (3, '部门非法'), (4, '货品非法')], default=0, verbose_name='错误原因')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '待递交'), (2, '已完成')], default=1, verbose_name='状态')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='部门')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='物料名称')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'oms-出库调整单查询',
                'verbose_name_plural': 'oms-出库调整单查询',
                'db_table': 'oms_convert_stockout',
            },
        ),
        migrations.CreateModel(
            name='CovertSOUnhandle',
            fields=[
            ],
            options={
                'verbose_name': 'oms-出库调整单未审核',
                'verbose_name_plural': 'oms-出库调整单未审核',
                'proxy': True,
                'indexes': [],
            },
            bases=('convert_console.covertso',),
        ),
    ]
