# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-23 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convert_console', '0005_covertso_covertsounhandle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covertso',
            old_name='ori_order_category',
            new_name='origin_order_category',
        ),
    ]
