# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-02-25 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_console', '0008_auto_20200224_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covertsi',
            name='create_date',
            field=models.DateTimeField(verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='covertsi',
            name='memorandum',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='covertsi',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '原始单缺漏'), (2, '入库数量大于采购数量'), (3, '保存库存错误'), (4, '货品错误'), (5, '采购单错误'), (6, '采购单数量错误')], default=0, verbose_name='错误标识'),
        ),
    ]
