# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptToVW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='单据状态')),
                ('centre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='department.CentreInfo', verbose_name='中心名称')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseVirtual', verbose_name='虚拟仓库')),
            ],
            options={
                'verbose_name': 'B-关联-部门2虚拟仓库',
                'verbose_name_plural': 'B-关联-部门2虚拟仓库',
                'db_table': 'base_rel_dept2vw',
            },
        ),
        migrations.CreateModel(
            name='DeptToW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='单据状态')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.CentreInfo', verbose_name='中心名称')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='实物仓库')),
            ],
            options={
                'verbose_name': 'B-关联-部门2实物仓库',
                'verbose_name_plural': 'B-关联-部门2实物仓库',
                'db_table': 'base_rel_dept2w',
            },
        ),
        migrations.AlterUniqueTogether(
            name='depttow',
            unique_together=set([('centre', 'warehouse')]),
        ),
        migrations.AlterUniqueTogether(
            name='depttovw',
            unique_together=set([('centre', 'warehouse')]),
        ),
    ]
