# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('department', '0001_initial'),
        ('company', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCodeToGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='单据状态')),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.BarCodeInfo', verbose_name='条码')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='货品')),
            ],
            options={
                'verbose_name': 'B-关联-条码2货品',
                'verbose_name_plural': 'B-关联-条码2货品',
                'db_table': 'base_rel_barcode2goods',
            },
        ),
        migrations.CreateModel(
            name='DepartmentToWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='单据状态')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='部门')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseGeneral', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'B-关联-部门2仓库',
                'verbose_name_plural': 'B-关联-部门2仓库',
                'db_table': 'base_rel_dept2ware',
            },
        ),
        migrations.CreateModel(
            name='ManuToWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='单据状态')),
                ('manufactory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ManuInfo', verbose_name='工厂')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseManu', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'B-关联-工厂2仓库',
                'verbose_name_plural': 'B-关联-工厂2仓库',
                'db_table': 'base_rel_manu2ware',
            },
        ),
        migrations.AlterUniqueTogether(
            name='manutowarehouse',
            unique_together=set([('manufactory', 'warehouse')]),
        ),
        migrations.AlterUniqueTogether(
            name='departmenttowarehouse',
            unique_together=set([('department', 'warehouse')]),
        ),
        migrations.AlterUniqueTogether(
            name='barcodetogoods',
            unique_together=set([('barcode', 'goods')]),
        ),
    ]
