# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-29 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttowarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseVirtual', verbose_name='仓库'),
        ),
    ]
