# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-11-19 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('relationship', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barcodetogoods',
            unique_together=set([('barcode', 'goods')]),
        ),
    ]
