# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20191124_2259'),
        ('company', '0002_mineinfo'),
        ('department', '0004_auto_20191125_0104'),
        ('relationship', '0002_auto_20191119_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentToWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='部门')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'B-关联-部门2仓库',
                'verbose_name_plural': 'B-关联-部门2仓库',
                'db_table': 'base_rel_dept2ware',
            },
        ),
        migrations.CreateModel(
            name='ManuToWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('manufactory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ManuInfo', verbose_name='工厂')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'B-关联-部门2仓库',
                'verbose_name_plural': 'B-关联-部门2仓库',
                'db_table': 'base_rel_manu2ware',
            },
        ),
        migrations.AlterUniqueTogether(
            name='manutowarehouse',
            unique_together=set([('manufactory', 'warehouse')]),
        ),
        migrations.AlterUniqueTogether(
            name='departmenttowarehouse',
            unique_together=set([('department', 'warehouse')]),
        ),
    ]
