# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-22 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_auto_20200222_1918'),
        ('department', '0002_auto_20200222_2136'),
        ('relationship', '0002_auto_20191229_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentToVWarehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('order_status', models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='单据状态')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='部门')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseVirtual', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'B-关联-部门2虚拟仓库',
                'verbose_name_plural': 'B-关联-部门2虚拟仓库',
                'db_table': 'base_rel_dept2vw',
            },
        ),
        migrations.AlterUniqueTogether(
            name='barcodetogoods',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='barcodetogoods',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='barcodetogoods',
            name='goods',
        ),
        migrations.AlterUniqueTogether(
            name='manutowarehouse',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='manutowarehouse',
            name='manufactory',
        ),
        migrations.RemoveField(
            model_name='manutowarehouse',
            name='warehouse',
        ),
        migrations.AlterModelOptions(
            name='departmenttowarehouse',
            options={'verbose_name': 'B-关联-部门2实物仓库', 'verbose_name_plural': 'B-关联-部门2实物仓库'},
        ),
        migrations.AlterField(
            model_name='departmenttowarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库'),
        ),
        migrations.AlterModelTable(
            name='departmenttowarehouse',
            table='base_rel_dept2w',
        ),
        migrations.DeleteModel(
            name='BarCodeToGoods',
        ),
        migrations.DeleteModel(
            name='ManuToWarehouse',
        ),
        migrations.AlterUniqueTogether(
            name='departmenttovwarehouse',
            unique_together=set([('department', 'warehouse')]),
        ),
    ]
