# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-22 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_auto_20200222_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttovwarehouse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', unique=True, verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='departmenttovwarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseVirtual', verbose_name='虚拟仓库'),
        ),
        migrations.AlterField(
            model_name='departmenttowarehouse',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='部门名称'),
        ),
        migrations.AlterField(
            model_name='departmenttowarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='实物仓库'),
        ),
    ]
