# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0003_auto_20191125_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttowarehouse',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='单据状态'),
        ),
        migrations.AddField(
            model_name='manutowarehouse',
            name='order_status',
            field=models.SmallIntegerField(choices=[(0, '取消'), (1, '正常')], default=1, verbose_name='单据状态'),
        ),
    ]
