# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0004_auto_20191125_0122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutowarehouse',
            options={'verbose_name': 'B-关联-工厂2仓库', 'verbose_name_plural': 'B-关联-工厂2仓库'},
        ),
    ]
