# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-25 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationship', '0005_auto_20191125_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenttowarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseGeneral', verbose_name='仓库'),
        ),
        migrations.AlterField(
            model_name='manutowarehouse',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseManu', verbose_name='仓库'),
        ),
    ]
