# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-03 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0005_auto_20191203_2024'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('distribution_order_id', models.CharField(max_length=50, verbose_name='分配单号')),
                ('quantity', models.IntegerField(verbose_name='分配数量')),
                ('memorandum', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.DepartmentInfo', verbose_name='部门')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='货品名称')),
            ],
            options={
                'verbose_name': 'OMS-预分配',
                'verbose_name_plural': 'OMS-预分配',
                'db_table': 'oms_pdb_distribution',
            },
        ),
    ]
