# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-04-25 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('goods', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptStockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('goods_id', models.CharField(db_index=True, max_length=60, verbose_name='物料编码')),
                ('quantity', models.IntegerField(verbose_name='库存')),
                ('memorandum', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '库存锁定'), (1, '正常销售')], default=1, verbose_name='库存状态')),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.CentreInfo', verbose_name='部门名称')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='货品名称')),
                ('vwarehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vware', to='warehouse.WarehouseVirtual', verbose_name='部门仓')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'WMS-库存-部门仓',
                'verbose_name_plural': 'WMS-库存-部门仓',
                'db_table': 'wms_stock_deptstock',
            },
        ),
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('goods_id', models.CharField(db_index=True, max_length=60, verbose_name='物料编码')),
                ('quantity', models.IntegerField(verbose_name='库存')),
                ('undistributed', models.IntegerField(verbose_name='未分配库存')),
                ('memorandum', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('order_status', models.SmallIntegerField(choices=[(0, '库存锁定'), (1, '等待分配'), (2, '分配完成')], default=1, verbose_name='库存状态')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='货品名称')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.WarehouseInfo', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'WMS-库存-实仓',
                'verbose_name_plural': 'WMS-库存-实仓',
                'db_table': 'wms_stock_stock',
            },
        ),
        migrations.CreateModel(
            name='MyDeptStock',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-库存-我的部门',
                'verbose_name_plural': 'WMS-库存-我的部门',
                'proxy': True,
                'indexes': [],
            },
            bases=('stock.deptstockinfo',),
        ),
        migrations.CreateModel(
            name='TransDeptStock',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-库存-中转仓',
                'verbose_name_plural': 'WMS-库存-中转仓',
                'proxy': True,
                'indexes': [],
            },
            bases=('stock.deptstockinfo',),
        ),
        migrations.AlterIndexTogether(
            name='stockinfo',
            index_together=set([('goods_name', 'warehouse')]),
        ),
        migrations.AlterIndexTogether(
            name='deptstockinfo',
            index_together=set([('centre', 'goods_name', 'warehouse', 'vwarehouse')]),
        ),
    ]
