# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-29 08:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDeptStock',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-库存-我的部门',
                'verbose_name_plural': 'WMS-库存-我的部门',
                'proxy': True,
                'indexes': [],
            },
            bases=('stock.deptstockinfo',),
        ),
        migrations.CreateModel(
            name='TransDeptStock',
            fields=[
            ],
            options={
                'verbose_name': 'WMS-库存-中转仓',
                'verbose_name_plural': 'WMS-库存-中转仓',
                'proxy': True,
                'indexes': [],
            },
            bases=('stock.deptstockinfo',),
        ),
    ]
