# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-28 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='stockinfo',
            index_together=set([('goods_name', 'warehouse')]),
        ),
    ]
