# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-28 20:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('goods', '0001_initial'),
        ('stock', '0002_auto_20191228_2052'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='deptstockinfo',
            index_together=set([('goods_name', 'warehouse', 'vwarehouse')]),
        ),
    ]
