# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-03-01 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('goods', '0001_initial'),
        ('warehouse', '0001_initial'),
        ('stock', '0003_auto_20200229_1145'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='deptstockinfo',
            index_together=set([('department', 'goods_name', 'warehouse', 'vwarehouse')]),
        ),
    ]
