# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-03 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
        ('company', '0002_mineinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriPurchaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('purchase_order_id', models.CharField(max_length=50, verbose_name='单据编号')),
                ('purchase_time', models.DateTimeField(max_length=50, verbose_name='采购时间')),
                ('supplier', models.CharField(max_length=70, verbose_name='供应商')),
                ('status', models.CharField(max_length=50, verbose_name='单据状态')),
                ('puchaser', models.CharField(max_length=60, verbose_name='采购组织')),
                ('is_cancel', models.CharField(max_length=50, verbose_name='关闭状态')),
                ('goods_unit', models.CharField(max_length=50, verbose_name='采购单位')),
                ('quantity', models.IntegerField(verbose_name='采购数量')),
                ('delivery_date', models.DateTimeField(verbose_name='交货日期')),
                ('goods_id', models.CharField(max_length=60, verbose_name='物料编码')),
                ('goods_name', models.CharField(max_length=60, verbose_name='物料名称')),
                ('business_process', models.CharField(blank=True, max_length=50, null=True, verbose_name='业务流程')),
                ('is_gift', models.CharField(max_length=50, verbose_name='是否赠品')),
                ('is_close', models.CharField(max_length=50, verbose_name='业务关闭')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '未递交'), (1, '已递交')], default=1, verbose_name='订单状态')),
                ('mistake_tag', models.SmallIntegerField(choices=[(0, '正常'), (1, '供应商未找到'), (2, '采购组织未找到'), (3, '货品未找到'), (4, '其他错误')], default=0, verbose_name='递交错误原因')),
            ],
            options={
                'verbose_name': 'OMS-原始采购单',
                'verbose_name_plural': 'OMS-原始采购单',
                'db_table': 'oms_purchase_oriorder',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('creator', models.CharField(blank=True, max_length=90, null=True, verbose_name='创建者')),
                ('purchase_order_id', models.CharField(max_length=50, verbose_name='单据编号')),
                ('purchase_time', models.DateTimeField(max_length=50, verbose_name='采购时间')),
                ('status', models.CharField(max_length=50, verbose_name='单据状态')),
                ('puchaser', models.CharField(max_length=50, verbose_name='采购组织')),
                ('is_cancel', models.CharField(max_length=50, verbose_name='关闭状态')),
                ('goods_unit', models.CharField(max_length=50, verbose_name='采购单位')),
                ('quantity', models.IntegerField(verbose_name='采购数量')),
                ('delivery_date', models.DateTimeField(verbose_name='交货日期')),
                ('goods_id', models.CharField(max_length=60, verbose_name='物料编码')),
                ('business_process', models.CharField(blank=True, max_length=50, null=True, verbose_name='业务流程')),
                ('is_gift', models.CharField(max_length=50, verbose_name='是否赠品')),
                ('is_close', models.CharField(max_length=50, verbose_name='业务关闭')),
                ('order_status', models.SmallIntegerField(choices=[(0, '已取消'), (1, '待生产'), (2, '在生产'), (3, '已完成')], default=1, verbose_name='订单状态')),
                ('goods_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInfo', verbose_name='物料名称')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.ManuInfo', verbose_name='供应商')),
            ],
            options={
                'verbose_name': 'OMS-采购单查询',
                'verbose_name_plural': 'OMS-采购单查询',
                'db_table': 'oms_purchase_order',
            },
        ),
        migrations.CreateModel(
            name='OriPurchasePending',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-未审核原始采购单',
                'verbose_name_plural': 'OMS-未审核原始采购单',
                'proxy': True,
                'indexes': [],
            },
            bases=('purchase.oripurchaseinfo',),
        ),
        migrations.CreateModel(
            name='PurchasePending',
            fields=[
            ],
            options={
                'verbose_name': 'OMS-采购单一览',
                'verbose_name_plural': 'OMS-采购单一览',
                'proxy': True,
                'indexes': [],
            },
            bases=('purchase.oripurchaseinfo',),
        ),
    ]
