# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-14 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinfo',
            name='complete_quantity',
            field=models.IntegerField(default=0, verbose_name='采购完成数量'),
        ),
        migrations.AlterField(
            model_name='oripurchaseinfo',
            name='mistake_tag',
            field=models.SmallIntegerField(choices=[(0, '正常'), (1, '货数被并'), (2, '导入重复'), (3, '工厂非法'), (4, '货品非法'), (5, '其他错误')], default=0, verbose_name='递交问题原因'),
        ),
    ]
