# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-12-29 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oripurchaseinfo',
            name='goods_id',
            field=models.CharField(db_index=True, max_length=60, verbose_name='物料编码'),
        ),
        migrations.AlterField(
            model_name='purchaseinfo',
            name='goods_id',
            field=models.CharField(db_index=True, max_length=60, verbose_name='物料编码'),
        ),
    ]
